export type TCurso = {
    curso: string;
    nota: number;
};
export type TEstudiante = {
    _id: string;
    nombre: string;
    apellido: string;
    email: string;
    direccion: string;
    tutor: string;
    telefono: string;
    año: string;
    division: string;
    docente: string;
    observaciones: string;
    cursos: TCurso[];
};
export const mockdata: TEstudiante[] = [
    {
        _id: "64e7f12345abc",
        nombre: "Bart",
        apellido: "Simpson",
        email: "eatmyshorts@email.com",
        direccion: "Av. Siempreviva 742",
        tutor: "Homero Simpson",
        telefono: "636-555-7334",
        año: "4°",
        division: "B",
        docente: "Edna Krabbaple",
        observaciones:
            "Bart es un niño curioso e hiperactivo, por lo que suele meterse en problemas jugando bromas para llamar la atención de los demás. Es destacable su talento para la música. Particularmente su dominio de la batería.",
        cursos: [
            { curso: "Matemática", nota: 4 },
            { curso: "Historia", nota: 3 },
            { curso: "Arte", nota: 10 },
        ],
    },
    {
        _id: "64e7f12346def",
        nombre: "Milhouse",
        apellido: "Van Houten",
        email: "milhouse.vanhouten@email.com",
        direccion: "Av. Siempreviva 743",
        tutor: "Kirk Van Houten",
        telefono: "636-555-7335",
        año: "4°",
        division: "B",
        docente: "Edna Krabbaple",
        observaciones:
            "Milhouse es el mejor amigo de Bart, un niño inteligente pero socialmente torpe. Usa anteojos gruesos y es muy leal a Bart, a menudo siguiéndolo en sus travesuras.",
        cursos: [
            { curso: "Matemática", nota: 7 },
            { curso: "Historia", nota: 6 },
            { curso: "Arte", nota: 5 },
        ],
    },
    {
        _id: "64e7f12347ghi",
        nombre: "Martin",
        apellido: "Prince",
        email: "martin.prince@email.com",
        direccion: "Av. Siempreviva 744",
        tutor: "Dick Whitmore",
        telefono: "636-555-7336",
        año: "4°",
        division: "B",
        docente: "Edna Krabbaple",
        observaciones:
            "Martin es el estudiante más inteligente de la clase, un niño extremadamente académico y precoz. Destaca en todas las materias y es frecuentemente objeto de burlas por su inteligencia.",
        cursos: [
            { curso: "Matemática", nota: 10 },
            { curso: "Historia", nota: 10 },
            { curso: "Arte", nota: 9 },
        ],
    },
    {
        _id: "64e7f12348jkl",
        nombre: "Nelson",
        apellido: "Muntz",
        email: "nelson.muntz@email.com",
        direccion: "Av. Siempreviva 745",
        tutor: "Ms. Muntz",
        telefono: "636-555-7337",
        año: "4°",
        division: "B",
        docente: "Edna Krabbaple",
        observaciones:
            "Nelson es el matón de la escuela, conocido por sus burlas y golpes. A pesar de su comportamiento agresivo, ocasionalmente muestra un lado más vulnerable.",
        cursos: [
            { curso: "Matemática", nota: 3 },
            { curso: "Historia", nota: 2 },
            { curso: "Arte", nota: 5 },
        ],
    },
    {
        _id: "64e7f12349mno",
        nombre: "Lisa",
        apellido: "Simpson",
        email: "lisa.simpson@email.com",
        direccion: "Av. Siempreviva 742",
        tutor: "Marge Simpson",
        telefono: "636-555-7338",
        año: "4°",
        division: "A",
        docente: "",
        observaciones:
            "Lisa es una niña extremadamente inteligente y comprometida con causas sociales. Sobresale en música y académicamente, siendo una estudiante modelo.",
        cursos: [
            { curso: "Matemática", nota: 10 },
            { curso: "Historia", nota: 10 },
            { curso: "Arte", nota: 10 },
        ],
    },
    {
        _id: "64e7f12350pqr",
        nombre: "Ralph",
        apellido: "Wiggum",
        email: "ralph.wiggum@email.com",
        direccion: "Av. Siempreviva 746",
        tutor: "Clancy Wiggum",
        telefono: "636-555-7339",
        año: "4°",
        division: "C",
        docente: "",
        observaciones:
            "Ralph es un niño inocente y algo ingenuo, conocido por sus comentarios cómicos y su percepción única del mundo. Hijo del jefe de policía Wiggum.",
        cursos: [
            { curso: "Matemática", nota: 2 },
            { curso: "Historia", nota: 1 },
            { curso: "Arte", nota: 6 },
        ],
    },
    {
        _id: "64e7f12351stu",
        nombre: "Chuck",
        apellido: "Berger",
        email: "chuck.berger@email.com",
        direccion: "Av. Siempreviva 747",
        tutor: "Mr. Berger",
        telefono: "636-555-7340",
        año: "4°",
        division: "B",
        docente: "Edna Krabbaple",
        observaciones:
            "Compañero de clase ocasionalmente mencionado, con poca información específica.",
        cursos: [
            { curso: "Matemática", nota: 5 },
            { curso: "Historia", nota: 4 },
            { curso: "Arte", nota: 5 },
        ],
    },
    {
        _id: "64e7f12352vwx",
        nombre: "Wendel",
        apellido: "Borton",
        email: "wendel.borton@email.com",
        direccion: "Av. Siempreviva 748",
        tutor: "Mrs. Borton",
        telefono: "636-555-7341",
        año: "4°",
        division: "B",
        docente: "Edna Krabbaple",
        observaciones: "Otro compañero de clase con información limitada.",
        cursos: [
            { curso: "Matemática", nota: 4 },
            { curso: "Historia", nota: 4 },
            { curso: "Arte", nota: 4 },
        ],
    },
    {
        _id: "64e7f12353yza",
        nombre: "Brittany",
        apellido: "Brockman",
        email: "brittany.brockman@email.com",
        direccion: "Av. Siempreviva 749",
        tutor: "Kent Brockman",
        telefono: "636-555-7342",
        año: "4°",
        division: "A",
        docente: "",
        observaciones: "Estudiante femenina de la escuela de Bart, con poca información detallada.",
        cursos: [
            { curso: "Matemática", nota: 6 },
            { curso: "Historia", nota: 5 },
            { curso: "Arte", nota: 7 },
        ],
    },
    {
        _id: "64e7f12354bcd",
        nombre: "Michael",
        apellido: "D'Amico",
        email: "michael.damico@email.com",
        direccion: "Av. Siempreviva 750",
        tutor: "Anthony D'Amico",
        telefono: "636-555-7343",
        año: "4°",
        division: "B",
        docente: "Edna Krabbaple",
        observaciones: "Otro compañero de clase con información limitada.",
        cursos: [
            { curso: "Matemática", nota: 5 },
            { curso: "Historia", nota: 5 },
            { curso: "Arte", nota: 5 },
        ],
    },
    {
        _id: "64e7f12355efg",
        nombre: "Amber",
        apellido: "Dempsey",
        email: "amber.dempsey@email.com",
        direccion: "Av. Siempreviva 751",
        tutor: "Mrs. Dempsey",
        telefono: "636-555-7344",
        año: "4°",
        division: "A",
        docente: "",
        observaciones: "Estudiante femenina de la escuela, con información limitada.",
        cursos: [
            { curso: "Matemática", nota: 6 },
            { curso: "Historia", nota: 6 },
            { curso: "Arte", nota: 6 },
        ],
    },
    {
        _id: "64e7f12356hij",
        nombre: "Maria",
        apellido: "Dominguez",
        email: "maria.dominguez@email.com",
        direccion: "Av. Siempreviva 752",
        tutor: "Mr. Dominguez",
        telefono: "636-555-7345",
        año: "4°",
        division: "B",
        docente: "Edna Krabbaple",
        observaciones: "Estudiante de origen hispano en la escuela de Bart.",
        cursos: [
            { curso: "Matemática", nota: 7 },
            { curso: "Historia", nota: 6 },
            { curso: "Arte", nota: 7 },
        ],
    },
    {
        _id: "64e7f12357klm",
        nombre: "Rod",
        apellido: "Flanders",
        email: "rod.flanders@email.com",
        direccion: "Av. Siempreviva 753",
        tutor: "Ned Flanders",
        telefono: "636-555-7346",
        año: "4°",
        division: "A",
        docente: "",
        observaciones:
            "Hijo de Ned Flanders, conocido por su educación religiosa y comportamiento ejemplar.",
        cursos: [
            { curso: "Matemática", nota: 8 },
            { curso: "Historia", nota: 7 },
            { curso: "Arte", nota: 8 },
        ],
    },
    {
        _id: "64e7f12358nop",
        nombre: "Todd",
        apellido: "Flanders",
        email: "todd.flanders@email.com",
        direccion: "Av. Siempreviva 753",
        tutor: "Ned Flanders",
        telefono: "636-555-7347",
        año: "4°",
        division: "A",
        docente: "",
        observaciones:
            "Hermano de Rod Flanders, también criado bajo los estrictos principios religiosos de su padre.",
        cursos: [
            { curso: "Matemática", nota: 7 },
            { curso: "Historia", nota: 8 },
            { curso: "Arte", nota: 7 },
        ],
    },
    {
        _id: "64e7f12359qrs",
        nombre: "Lewis",
        apellido: "Clark",
        email: "lewis.clark@email.com",
        direccion: "Av. Siempreviva 754",
        tutor: "Mrs. Clark",
        telefono: "636-555-7348",
        año: "4°",
        division: "B",
        docente: "Edna Krabbaple",
        observaciones: "Otro compañero de clase de Bart con información limitada.",
        cursos: [
            { curso: "Matemática", nota: 5 },
            { curso: "Historia", nota: 5 },
            { curso: "Arte", nota: 5 },
        ],
    },
    {
        _id: "64e7f12360tuv",
        nombre: "Jessica",
        apellido: "Lovejoy",
        email: "jessica.lovejoy@email.com",
        direccion: "Av. Siempreviva 755",
        tutor: "Helen Lovejoy",
        telefono: "636-555-7349",
        año: "4°",
        division: "A",
        docente: "",
        observaciones:
            "Hija del reverendo Lovejoy, conocida por su apariencia de niña buena pero con un lado travieso.",
        cursos: [
            { curso: "Matemática", nota: 7 },
            { curso: "Historia", nota: 6 },
            { curso: "Arte", nota: 8 },
        ],
    },
    {
        _id: "64e7f12361wxy",
        nombre: "Janey",
        apellido: "Powell",
        email: "janey.powell@email.com",
        direccion: "Av. Siempreviva 756",
        tutor: "Mr. Powell",
        telefono: "636-555-7350",
        año: "4°",
        division: "A",
        docente: "",
        observaciones: "Compañera de clase de Bart, con poca información detallada.",
        cursos: [
            { curso: "Matemática", nota: 6 },
            { curso: "Historia", nota: 5 },
            { curso: "Arte", nota: 7 },
        ],
    },
    {
        _id: "64e7f12362zab",
        nombre: "Sherri",
        apellido: "Mackleberry",
        email: "sherri.mackleberry@email.com",
        direccion: "Av. Siempreviva 757",
        tutor: "Mrs. Mackleberry",
        telefono: "636-555-7351",
        año: "4°",
        division: "A",
        docente: "",
        observaciones: "Una de las gemelas Mackleberry, conocida por su personalidad.",
        cursos: [
            { curso: "Matemática", nota: 7 },
            { curso: "Historia", nota: 6 },
            { curso: "Arte", nota: 8 },
        ],
    },
    {
        _id: "64e7f12363cde",
        nombre: "Terri",
        apellido: "Mackleberry",
        email: "terri.mackleberry@email.com",
        direccion: "Av. Siempreviva 757",
        tutor: "Mrs. Mackleberry",
        telefono: "636-555-7352",
        año: "4°",
        division: "A",
        docente: "",
        observaciones: "La otra gemela Mackleberry, similar a su hermana Sherri.",
        cursos: [
            { curso: "Matemática", nota: 7 },
            { curso: "Historia", nota: 6 },
            { curso: "Arte", nota: 8 },
        ],
    },
    {
        _id: "64e7f12364fgh",
        nombre: "Üter",
        apellido: "Zörker",
        email: "ueter.zorker@email.com",
        direccion: "Av. Siempreviva 758",
        tutor: "Willie McDougal",
        telefono: "636-555-7353",
        año: "4°",
        division: "B",
        docente: "Edna Krabbaple",
        observaciones:
            "Estudiante de intercambio alemán en la escuela de Bart, conocido por su personalidad peculiar.",
        cursos: [
            { curso: "Matemática", nota: 6 },
            { curso: "Historia", nota: 5 },
            { curso: "Arte", nota: 7 },
        ],
    },
];
